[package]
name = "bili-sync"
version = "2.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
strum = { version = "0.26", features = ["derive"] }
async-stream = "0.3.5"
futures-core = "0.3"
futures-util = "0.3.30"

[profile.release]
strip = true
