[package]
name = "bili-sync"
version = "2.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
sea-orm = { version = "0.12", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
    "macros",
] }
serde_json = "1.0"
reqwest = { version = "0.12.0", features = ["json", "stream", "cookies"] }
cookie = { version = "0.18.0", features = ["percent-encode"] }
tokio = { version = "1", features = ["full"] }
strum = { version = "0.26", features = ["derive"] }
async-stream = "0.3.5"
futures-core = "0.3"
futures-util = "0.3.30"
rsa = { version = "0.9.6", features = ["sha2"] }
hex = "0.4.3"
rand = "0.8.5"
regex = "1.10.3"
chrono = { version = "0.4.35", features = ["serde"] }
env_logger = "0.11.3"
log = "0.4.21"
tinytemplate = "1.2.1"
futures = "0.3.30"
quick-xml = { version = "0.31.0", features = ["async-tokio"] }
entity = { path = "entity" }
migration = { path = "migration" }

[workspace]
members = [".", "entity", "migration"]

[profile.release]
strip = true
